org: antoniocot
service: api-tokens

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::316129865556:role/LabRole
  environment:
    TOKENS_TABLE: TABLA-TOKENS_ACCESO-${sls:stage}
    GSI: ${sls:stage}-tokenAcces-UserIdIndex_at-index

functions:
  ValidarToken:
    handler: ValidarToken.lambda_handler
    events:
      - http:
          path: /tokens/validar
          method: post
          cors: true
          integration: lambda

resources:
  Resources:
    TokensAccesoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TOKENS_TABLE}
        AttributeDefinitions:
          - AttributeName: token
            AttributeType: S
          - AttributeName: usuario_id
            AttributeType: S
        KeySchema:
          - AttributeName: token
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.GSI}
            KeySchema:
              - AttributeName: usuario_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true              