org: antoniocot
service: api-usuarios

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::316129865556:role/LabRole
  region: us-east-1
  profile: default
  environment:
    USUARIOS_TABLE: TABLA-USUARIOS-${sls:stage}
    TOKENS_TABLE: TABLA-TOKENS_ACCESO-${sls:stage}
    GSI_EMAIL: email-index-${sls:stage}  # Índice de email
    GSI_DNI: dni-index-${sls:stage}  # Índice de dni

functions:
  CrearUsuario:
    handler: lambdas/CrearUsuario.lambda_handler
    events:
      - http:
          path: /usuarios/crear
          method: post
          cors: true
          integration: lambda

  ListarUsuarios:
    handler: lambdas/ListarUsuarios.lambda_handler
    events:
      - http:
          path: /usuarios/listar
          method: post
          cors: true
          integration: lambda

  BuscarUsuario:
    handler: lambdas/BuscarUsuario.lambda_handler
    events:
      - http:
          path: /usuarios/buscar
          method: post
          cors: true
          integration: lambda

  EliminarUsuario:
    handler: lambdas/EliminarUsuario.lambda_handler
    events:
      - http:
          path: /usuarios/eliminar
          method: delete
          cors: true
          integration: lambda

  ModificarUsuario:
    handler: lambdas/ModificarUsuario.lambda_handler
    events:
      - http:
          path: /usuarios/modificar
          method: put
          cors: true
          integration: lambda

  LoginUsuario:
    handler: lambdas/LoginUsuario.lambda_handler
    events:
      - http:
          path: /usuarios/login
          method: post
          cors: true
          integration: lambda

resources:
  Resources:
    UsuariosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USUARIOS_TABLE}
        AttributeDefinitions:
          - AttributeName: usuario_id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
          - AttributeName: dni
            AttributeType: S
        KeySchema:
          - AttributeName: usuario_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.GSI_EMAIL}
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: ${self:provider.environment.GSI_DNI}
            KeySchema:
              - AttributeName: dni
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true